[build-system]
requires = ["scikit-build-core>=0.10", "cmake", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.pytest.ini_options]
addopts = """
    --ignore=Release
    --ignore=Debug
"""
