[build-system]
requires = ["setuptools >= 40.9.0","wheel", "cmake", "cmake_setuptools", "ninja"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = """
    --ignore=Release
    --ignore=Debug
"""
